lista = list()
n = int(input('Digite um valor: '))
lista.append(n)
print('Adicionado ao final da lista...')
n = int(input('Digite um valor: '))
lista.insert(0, n)
print('Adicionado na posição 0 da lista...')
n = int(input('Digite um valor: '))
lista.insert(1, n)
print('Adicionado na posição 1 da lista...')
n = int(input('Digite um valor: '))
lista.append(n)
print('Adicionado ao final da lista...')
n = int(input('Digite um valor: '))
lista.insert(0, n)
print('Adicionado na posição 0 da lista...')
print(f'Os valores digitados em ordem foram {lista}.'.replace('[', '').replace(']', ''))
